# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lift_control.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mwindow_lift_control(object):
    def setupUi(self, mwindow_lift_control):
        mwindow_lift_control.setObjectName("mwindow_lift_control")
        mwindow_lift_control.resize(800, 800)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        mwindow_lift_control.setFont(font)
        self.central_widget = QtWidgets.QWidget(mwindow_lift_control)
        self.central_widget.setObjectName("central_widget")
        self.layoutWidget = QtWidgets.QWidget(self.central_widget)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 751, 751))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vert_layout_lift_control = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vert_layout_lift_control.setContentsMargins(0, 0, 0, 0)
        self.vert_layout_lift_control.setObjectName("vert_layout_lift_control")
        self.lbl_lift_control = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_lift_control.setFont(font)
        self.lbl_lift_control.setObjectName("lbl_lift_control")
        self.vert_layout_lift_control.addWidget(self.lbl_lift_control)
        self.hori_line_lift_control = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_lift_control.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_lift_control.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_lift_control.setObjectName("hori_line_lift_control")
        self.vert_layout_lift_control.addWidget(self.hori_line_lift_control)
        self.hori_layout_nav = QtWidgets.QHBoxLayout()
        self.hori_layout_nav.setObjectName("hori_layout_nav")
        self.btn_new_sim = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_new_sim.setObjectName("btn_new_sim")
        self.hori_layout_nav.addWidget(self.btn_new_sim, 0, QtCore.Qt.AlignLeft)
        self.btn_run_sim = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_run_sim.setObjectName("btn_run_sim")
        self.hori_layout_nav.addWidget(self.btn_run_sim, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hori_layout_nav.addItem(spacerItem)
        self.vert_layout_lift_control.addLayout(self.hori_layout_nav)
        self.hori_line_nav = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_nav.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_nav.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_nav.setObjectName("hori_line_nav")
        self.vert_layout_lift_control.addWidget(self.hori_line_nav)
        self.lbl_num_in_lift = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_num_in_lift.setObjectName("lbl_num_in_lift")
        self.vert_layout_lift_control.addWidget(self.lbl_num_in_lift)
        self.lbl_total_delivered = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_total_delivered.setObjectName("lbl_total_delivered")
        self.vert_layout_lift_control.addWidget(self.lbl_total_delivered)
        self.lbl_total_moves = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_total_moves.setObjectName("lbl_total_moves")
        self.vert_layout_lift_control.addWidget(self.lbl_total_moves)
        self.hori_line_summary = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_summary.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_summary.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_summary.setObjectName("hori_line_summary")
        self.vert_layout_lift_control.addWidget(self.hori_line_summary)
        self.lbl_num_in_lift_2 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_num_in_lift_2.setObjectName("lbl_num_in_lift_2")
        self.vert_layout_lift_control.addWidget(self.lbl_num_in_lift_2)
        self.hori_line_status = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_status.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_status.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_status.setObjectName("hori_line_status")
        self.vert_layout_lift_control.addWidget(self.hori_line_status)
        self.grid_layout_sim = QtWidgets.QGridLayout()
        self.grid_layout_sim.setObjectName("grid_layout_sim")
        self.lbl_floor7 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_floor7.setObjectName("lbl_floor7")
        self.grid_layout_sim.addWidget(self.lbl_floor7, 7, 1, 1, 1)
        self.lbl_floor1_5 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_floor1_5.setObjectName("lbl_floor1_5")
        self.grid_layout_sim.addWidget(self.lbl_floor1_5, 5, 0, 1, 1)
        self.lbl_waiting_1 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_waiting_1.setObjectName("lbl_waiting_1")
        self.grid_layout_sim.addWidget(self.lbl_waiting_1, 1, 0, 1, 1)
        self.lbl_floor6 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_floor6.setObjectName("lbl_floor6")
        self.grid_layout_sim.addWidget(self.lbl_floor6, 6, 1, 1, 1)
        self.lbl_num_waiting = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_num_waiting.setFont(font)
        self.lbl_num_waiting.setObjectName("lbl_num_waiting")
        self.grid_layout_sim.addWidget(self.lbl_num_waiting, 0, 0, 1, 1)
        self.lbl_floor4 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_floor4.setObjectName("lbl_floor4")
        self.grid_layout_sim.addWidget(self.lbl_floor4, 4, 1, 1, 1)
        self.lbl_floor3 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_floor3.setObjectName("lbl_floor3")
        self.grid_layout_sim.addWidget(self.lbl_floor3, 3, 1, 1, 1)
        self.lbl_floor1_6 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_floor1_6.setObjectName("lbl_floor1_6")
        self.grid_layout_sim.addWidget(self.lbl_floor1_6, 6, 0, 1, 1)
        self.lbl_delivered10 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_delivered10.setObjectName("lbl_delivered10")
        self.grid_layout_sim.addWidget(self.lbl_delivered10, 10, 1, 1, 1)
        self.lbl_floor1_4 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_floor1_4.setObjectName("lbl_floor1_4")
        self.grid_layout_sim.addWidget(self.lbl_floor1_4, 3, 0, 1, 1)
        self.lbl_waiting2 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_waiting2.setObjectName("lbl_waiting2")
        self.grid_layout_sim.addWidget(self.lbl_waiting2, 2, 0, 1, 1)
        self.lbl_floor9 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_floor9.setObjectName("lbl_floor9")
        self.grid_layout_sim.addWidget(self.lbl_floor9, 9, 1, 1, 1)
        self.lbl_floor2 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_floor2.setObjectName("lbl_floor2")
        self.grid_layout_sim.addWidget(self.lbl_floor2, 2, 1, 1, 1)
        self.lbl_floor8 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_floor8.setObjectName("lbl_floor8")
        self.grid_layout_sim.addWidget(self.lbl_floor8, 8, 1, 1, 1)
        self.lbl_sim_placeholder = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_sim_placeholder.setFont(font)
        self.lbl_sim_placeholder.setObjectName("lbl_sim_placeholder")
        self.grid_layout_sim.addWidget(self.lbl_sim_placeholder, 0, 2, 1, 1)
        self.lbl_delivered1 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_delivered1.setObjectName("lbl_delivered1")
        self.grid_layout_sim.addWidget(self.lbl_delivered1, 1, 1, 1, 1)
        self.lbl_floor5 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_floor5.setObjectName("lbl_floor5")
        self.grid_layout_sim.addWidget(self.lbl_floor5, 5, 1, 1, 1)
        self.lbl_num_delivered = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_num_delivered.setFont(font)
        self.lbl_num_delivered.setObjectName("lbl_num_delivered")
        self.grid_layout_sim.addWidget(self.lbl_num_delivered, 0, 1, 1, 1)
        self.lbl_ = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_.setObjectName("lbl_")
        self.grid_layout_sim.addWidget(self.lbl_, 4, 0, 1, 1)
        self.lbl_floor1_7 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_floor1_7.setObjectName("lbl_floor1_7")
        self.grid_layout_sim.addWidget(self.lbl_floor1_7, 7, 0, 1, 1)
        self.lbl_waiting8 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_waiting8.setObjectName("lbl_waiting8")
        self.grid_layout_sim.addWidget(self.lbl_waiting8, 8, 0, 1, 1)
        self.lbl_waiting9 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_waiting9.setObjectName("lbl_waiting9")
        self.grid_layout_sim.addWidget(self.lbl_waiting9, 9, 0, 1, 1)
        self.lbl_floor1_9 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_floor1_9.setObjectName("lbl_floor1_9")
        self.grid_layout_sim.addWidget(self.lbl_floor1_9, 10, 0, 1, 1)
        self.vert_layout_lift_control.addLayout(self.grid_layout_sim)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.vert_layout_lift_control.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vert_layout_lift_control.addItem(spacerItem1)
        mwindow_lift_control.setCentralWidget(self.central_widget)
        self.status_bar = QtWidgets.QStatusBar(mwindow_lift_control)
        self.status_bar.setObjectName("status_bar")
        mwindow_lift_control.setStatusBar(self.status_bar)

        self.retranslateUi(mwindow_lift_control)
        QtCore.QMetaObject.connectSlotsByName(mwindow_lift_control)

    def retranslateUi(self, mwindow_lift_control):
        _translate = QtCore.QCoreApplication.translate
        mwindow_lift_control.setWindowTitle(_translate("mwindow_lift_control", "Lift Control"))
        self.lbl_lift_control.setText(_translate("mwindow_lift_control", "Lift Control"))
        self.btn_new_sim.setText(_translate("mwindow_lift_control", "New Simulation"))
        self.btn_run_sim.setText(_translate("mwindow_lift_control", "Run Simulation"))
        self.lbl_num_in_lift.setText(_translate("mwindow_lift_control", "Number of People in Lift: "))
        self.lbl_total_delivered.setText(_translate("mwindow_lift_control", "Total Number of People Delivered:"))
        self.lbl_total_moves.setText(_translate("mwindow_lift_control", "Total Number of Moves:"))
        self.lbl_num_in_lift_2.setText(_translate("mwindow_lift_control", "Number of People Currently in Lift:"))
        self.lbl_floor7.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_floor1_5.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_waiting_1.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_floor6.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_num_waiting.setText(_translate("mwindow_lift_control", "Number of People Waiting:"))
        self.lbl_floor4.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_floor3.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_floor1_6.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_delivered10.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_floor1_4.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_waiting2.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_floor9.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_floor2.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_floor8.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_sim_placeholder.setText(_translate("mwindow_lift_control", "Lift Floors:"))
        self.lbl_delivered1.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_floor5.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_num_delivered.setText(_translate("mwindow_lift_control", "Number of People Delivered:"))
        self.lbl_.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_floor1_7.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_waiting8.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_waiting9.setText(_translate("mwindow_lift_control", "0"))
        self.lbl_floor1_9.setText(_translate("mwindow_lift_control", "0"))
        self.label.setText(_translate("mwindow_lift_control", "(White blocks represent floors, and red blocks represent floors with the lift on it.)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mwindow_lift_control = QtWidgets.QMainWindow()
    ui = Ui_mwindow_lift_control()
    ui.setupUi(mwindow_lift_control)
    mwindow_lift_control.show()
    sys.exit(app.exec_())
