# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sim_6_floors.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mwindow_sim_6_floors(object):
    def setupUi(self, mwindow_sim_6_floors):
        mwindow_sim_6_floors.setObjectName("mwindow_sim_6_floors")
        mwindow_sim_6_floors.resize(800, 800)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        mwindow_sim_6_floors.setFont(font)
        self.central_widget = QtWidgets.QWidget(mwindow_sim_6_floors)
        self.central_widget.setObjectName("central_widget")
        self.layoutWidget = QtWidgets.QWidget(self.central_widget)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 751, 751))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vert_layout_lift_control = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vert_layout_lift_control.setContentsMargins(0, 0, 0, 0)
        self.vert_layout_lift_control.setObjectName("vert_layout_lift_control")
        self.lbl_lift_control = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_lift_control.setFont(font)
        self.lbl_lift_control.setObjectName("lbl_lift_control")
        self.vert_layout_lift_control.addWidget(self.lbl_lift_control)
        self.hori_line_lift_control = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_lift_control.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_lift_control.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_lift_control.setObjectName("hori_line_lift_control")
        self.vert_layout_lift_control.addWidget(self.hori_line_lift_control)
        self.hori_layout_nav = QtWidgets.QHBoxLayout()
        self.hori_layout_nav.setObjectName("hori_layout_nav")
        self.btn_generate_new_sim = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_generate_new_sim.setObjectName("btn_generate_new_sim")
        self.hori_layout_nav.addWidget(self.btn_generate_new_sim)
        self.vert_line_buttons = QtWidgets.QFrame(self.layoutWidget)
        self.vert_line_buttons.setFrameShape(QtWidgets.QFrame.VLine)
        self.vert_line_buttons.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vert_line_buttons.setObjectName("vert_line_buttons")
        self.hori_layout_nav.addWidget(self.vert_line_buttons)
        self.btn_run_sim_naive = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_run_sim_naive.setObjectName("btn_run_sim_naive")
        self.hori_layout_nav.addWidget(self.btn_run_sim_naive, 0, QtCore.Qt.AlignLeft)
        self.btn_run_sim_improved = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_run_sim_improved.setObjectName("btn_run_sim_improved")
        self.hori_layout_nav.addWidget(self.btn_run_sim_improved)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hori_layout_nav.addItem(spacerItem)
        self.vert_layout_lift_control.addLayout(self.hori_layout_nav)
        self.hori_line_nav = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_nav.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_nav.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_nav.setObjectName("hori_line_nav")
        self.vert_layout_lift_control.addWidget(self.hori_line_nav)
        self.lbl_num_delivered = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_num_delivered.setObjectName("lbl_num_delivered")
        self.vert_layout_lift_control.addWidget(self.lbl_num_delivered)
        self.lbl_distance_travelled = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_distance_travelled.setObjectName("lbl_distance_travelled")
        self.vert_layout_lift_control.addWidget(self.lbl_distance_travelled)
        self.hori_line_summary = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_summary.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_summary.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_summary.setObjectName("hori_line_summary")
        self.vert_layout_lift_control.addWidget(self.hori_line_summary)
        self.lbl_num_in_lift = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_num_in_lift.setObjectName("lbl_num_in_lift")
        self.vert_layout_lift_control.addWidget(self.lbl_num_in_lift)
        self.hori_line_status = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_status.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_status.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_status.setObjectName("hori_line_status")
        self.vert_layout_lift_control.addWidget(self.hori_line_status)
        self.hori_line_sim = QtWidgets.QFrame(self.layoutWidget)
        self.hori_line_sim.setFrameShape(QtWidgets.QFrame.HLine)
        self.hori_line_sim.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hori_line_sim.setObjectName("hori_line_sim")
        self.vert_layout_lift_control.addWidget(self.hori_line_sim)
        self.lbl_key = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.lbl_key.setFont(font)
        self.lbl_key.setObjectName("lbl_key")
        self.vert_layout_lift_control.addWidget(self.lbl_key)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vert_layout_lift_control.addItem(spacerItem1)
        mwindow_sim_6_floors.setCentralWidget(self.central_widget)

        self.retranslateUi(mwindow_sim_6_floors)
        QtCore.QMetaObject.connectSlotsByName(mwindow_sim_6_floors)

    def retranslateUi(self, mwindow_sim_6_floors):
        _translate = QtCore.QCoreApplication.translate
        mwindow_sim_6_floors.setWindowTitle(_translate("mwindow_sim_6_floors", "Simulation (Non-Visual) - Lift Control"))
        self.lbl_lift_control.setText(_translate("mwindow_sim_6_floors", "Lift Control - Simulation (Non-Visual)"))
        self.btn_generate_new_sim.setText(_translate("mwindow_sim_6_floors", "Generate New Simulation"))
        self.btn_run_sim_naive.setText(_translate("mwindow_sim_6_floors", "Run Simulation (Naive)"))
        self.btn_run_sim_improved.setText(_translate("mwindow_sim_6_floors", "Run Simulation (Improved)"))
        self.lbl_num_delivered.setText(_translate("mwindow_sim_6_floors", "Number of People Delivered: 0"))
        self.lbl_distance_travelled.setText(_translate("mwindow_sim_6_floors", "Total Distance Travelled: 0"))
        self.lbl_num_in_lift.setText(_translate("mwindow_sim_6_floors", "Number of People in Lift: 0"))
        self.lbl_key.setText(_translate("mwindow_sim_6_floors", "(White blocks represent floors, and red blocks represent floors with the lift on it.)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mwindow_sim_6_floors = QtWidgets.QMainWindow()
    ui = Ui_mwindow_sim_6_floors()
    ui.setupUi(mwindow_sim_6_floors)
    mwindow_sim_6_floors.show()
    sys.exit(app.exec_())
